services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: loop-spring-dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: ${LOOP_DB_DEV_URL}
      DB_USERNAME: ${LOOP_DB_DEV_USERNAME}
      DB_PASSWORD: ${LOOP_DB_DEV_PASSWORD}

  redis:
    container_name: loop-redis-dev

  nginx:
    container_name: loop-nginx-dev